# Generated by Django 3.2.2 on 2021-05-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, default='', max_length=100)),
                ('organizer', models.CharField(blank=True, default='', max_length=100)),
                ('hasDate', models.BooleanField(blank=True, default=False)),
                ('dateStart', models.DateField(blank=True)),
                ('dateEnd', models.DateField(blank=True)),
                ('isRecurringWeekly', models.BooleanField(blank=True, default=False)),
                ('recurringDay', models.CharField(blank=True, default='', max_length=100)),
                ('isRecurringMonthly', models.BooleanField(blank=True, default=False)),
                ('isRecurringAnnually', models.BooleanField(blank=True, default=False)),
                ('isBirthday', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
