# Generated by Django 3.2.2 on 2021-05-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateEnd',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateStart',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hasDate',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hashtag',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='isBirthday',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='isRecurringAnnually',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='isRecurringMonthly',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='isRecurringWeekly',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurringDay',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
