# Generated by Django 3.2.2 on 2021-05-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210507_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='isBirthday',
        ),
    ]
