# Generated by Django 3.2.2 on 2021-05-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20210507_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='isRecurringAnnually',
        ),
        migrations.RemoveField(
            model_name='event',
            name='isRecurringMonthly',
        ),
        migrations.RemoveField(
            model_name='event',
            name='isRecurringWeekly',
        ),
        migrations.AddField(
            model_name='event',
            name='recurring',
            field=models.CharField(blank=True, choices=[('NONE', 'no'), ('WEEKLY', 'weekly'), ('MONTHLY', 'monthly'), ('ANNUALLY', 'annually')], default='NONE', max_length=10, null=True, verbose_name='Recurring?'),
        ),
    ]
