# Generated by Django 3.2.2 on 2021-05-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210507_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dateEnd',
            field=models.DateField(blank=True, null=True, verbose_name='End Date (optional)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='dateStart',
            field=models.DateField(blank=True, null=True, verbose_name='Date Start (optional)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hashtag',
            field=models.CharField(default='#', max_length=200, verbose_name='Hashtag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, default='@', max_length=100, null=True, verbose_name='Hashtag Organizer (optional)'),
        ),
    ]
