# Generated by Django 3.2.2 on 2021-05-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagramName', models.CharField(max_length=100)),
                ('plushieName', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
