# Generated by Django 3.2.2 on 2021-05-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='date',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='instagramName',
            field=models.CharField(max_length=100, verbose_name='Instagram Account Name'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='plushieName',
            field=models.CharField(max_length=100, verbose_name='Name of the Plushie'),
        ),
    ]
